# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    trusted_proxies: '127.0.0.1'
    http_method_override: true
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session:
            enabled: true
            storage_factory_id: session.storage.factory.native
            cookie_secure: auto # ou false si tu es en local
            cookie_samesite: lax

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
